spring:
  cache:
    type: simple
  datasource:
    url: jdbc:oracle:thin:@oracle.fiap.com.br:1521:orcl
    username: ${DB_USER:rm556795}
    password: ${DB_PASS:110703}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        format_sql: true

  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USER:guest}
    password: ${RABBIT_PASS:guest}
    listener:
      simple:
        auto-startup: true

  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: ${JWT_SECRET:12345678901234567890123456789012}

groq:
  api:
    key: ${GROQ_KEY}
  model: llama-3.1-8b-instant
  temperature: 0.2

server:
  port: ${PORT:8080}